# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noshpit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='place_id',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
