# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noshpit', '0002_auto_20170713_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
