# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noshpit', '0004_pitphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='noshpit.Pit'),
            preserve_default=False,
        ),
    ]
