# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 01:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noshpit', '0005_user_pit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('pit', 'user', 'location')]),
        ),
    ]
