# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noshpit', '0006_auto_20170720_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='pit',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='noshpit.Location'),
        ),
    ]
