# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noshpit', '0007_pit_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
